name: EventManager
version: '1.2'
main: com.eventmanager.plugin.EventManager
api-version: '26.1'
commands:
  Manager:
    usage: /Manager
    description: Opens the Event Manager GUI
    permission: manager.admin
